# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IMUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('photo', models.CharField(blank=True, default='', max_length=100)),
                ('bgimg', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
