# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0003_auto_20161026_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='imuser',
            name='rctoken',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='imuser',
            name='token',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
