# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0004_auto_20161026_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='imuser',
            name='password',
            field=models.CharField(default=123456, max_length=100),
            preserve_default=False,
        ),
    ]
