# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0005_imuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='imuser',
            name='friends',
            field=models.ManyToManyField(related_name='_imuser_friends_+', to='relationship.IMUser'),
        ),
    ]
