# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0006_imuser_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imuser',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_imuser_friends_+', to='relationship.IMUser'),
        ),
    ]
