# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0007_auto_20161026_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='imuser',
            name='note',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
