# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0008_imuser_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='imuser',
            name='wechatid',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
